"""Generate the two pasteable signatures from `signature.html`.

The copy lives in `signature.html` and nowhere else: this reads the name, role,
email address and site out of that page's EDIT ME block and writes the table
markup around them. Edit `signature.html`, run `render.sh`, and the card PNG and
both pasteable signatures stay in step.

    signature-email.html          images loaded from https://thetide.co.nz
    signature-email-inline.html   images baked into the file as data: URIs

They are the same signature; the difference is where the three little PNGs come
from. The hosted one is the better signature — small, and it renders in every
client including Outlook on Windows — but it shows broken images until the site
carrying `public/signature/` has been deployed. The inline one works the moment
you paste it, at the cost of ~150KB on every email you send and of Outlook on
Windows, which refuses to load a data: URI in an image. Use the inline one until
the site is deployed, then switch.

Why the markup looks the way it does — mail clients are not browsers:

  * Tables, not flexbox or grid. Outlook on Windows renders through Word, which
    has no flex layout at all.
  * Inline styles only. Gmail strips <style> blocks out of a pasted signature.
  * The photo and the name are images. The photo is round because the PNG is
    round (Outlook drops border-radius on images), and the name is an image
    because Baloo 2 is a web font, which no mail client will download.
"""

import base64
import html
import re
from pathlib import Path

from PIL import Image

HERE = Path(__file__).parent
SOURCE = HERE / 'signature.html'
ASSETS = HERE.parent.parent / 'public' / 'signature'

BASE = 'https://thetide.co.nz'

INK = '#23313c'
SEA = '#45758c'
SKY = '#a2c5d3'
SLATE = '#5a6672'
SAND_LIGHT = '#faf5ea'

FONT = "'Helvetica Neue', Helvetica, Arial, sans-serif"


def grab(pattern: str) -> str:
    m = re.search(pattern, SOURCE.read_text(), re.S)
    if not m:
        raise SystemExit(f'could not find {pattern!r} in signature.html')
    return re.sub(r'\s+', ' ', m.group(1)).strip()


def hosted(png: str) -> str:
    return f'{BASE}/signature/{png}'


def inline(png: str) -> str:
    data = base64.b64encode((ASSETS / png).read_bytes()).decode()
    return f'data:image/png;base64,{data}'


def build(src, note: str) -> str:
    """The signature's markup, with `src` deciding where each PNG comes from."""
    name = grab(r'<p class="name">(.*?)</p>')
    role = grab(r'<p class="role">(.*?)<span>')
    outlet = grab(r'<em>(.*?)</em>')
    email = grab(r'</svg>\s*(\S+@\S+?)\s*</div>')
    site = grab(r'</svg>\s*((?:www\.)?[\w.-]+\.\w{2,}(?:\.\w{2})?)\s*</div>\s*</div>')

    # name.png is rendered at 2x and placed at half its pixel size, so it stays
    # sharp on a retina screen.
    name_w, name_h = (d // 2 for d in Image.open(ASSETS / 'name.png').size)

    e = html.escape
    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>The Tide — email signature (paste this)</title>
  </head>
  <body style="margin:0;padding:24px;background:#ffffff">
    <!-- GENERATED by build-email.py from signature.html — edit that page, then
         run render.sh. Changes made here are overwritten on the next render.

         {note}

         To install: open this file in a browser, select the whole card, copy,
         and paste it into your mail client's signature box. Paste as rich text;
         "paste and match style" strips the layout. -->
    <table cellpadding="0" cellspacing="0" border="0" role="presentation"
           style="border-collapse:separate;border-spacing:0;background:{SAND_LIGHT};border:2px solid rgba(69,117,140,0.3);border-radius:14px;font-family:{FONT}">
      <tr>
        <td style="padding:18px 22px 18px 20px" valign="middle">
          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse">
            <tr>
              <td valign="middle" style="padding-right:20px">
                <img src="{src('portrait.png')}" width="112" height="112" alt="{e(name)}"
                     style="display:block;width:112px;height:112px;border:0" />
              </td>
              <td valign="middle" style="font-family:{FONT}">
                <img src="{src('name.png')}" width="{name_w}" height="{name_h}" alt="{e(name)}"
                     style="display:block;width:{name_w}px;height:{name_h}px;border:0" />
                <div style="height:2px;margin:9px 0 10px;background:rgba(69,117,140,0.32);border-radius:1px"></div>
                <div style="font-family:{FONT};font-size:12px;font-weight:bold;letter-spacing:1.6px;text-transform:uppercase;color:{INK};line-height:1.2">
                  {e(role)} <span style="color:{SKY};font-weight:normal">&nbsp;|&nbsp;</span> <span style="color:{SEA}">{e(outlet)}</span>
                </div>
                <div style="font-family:{FONT};font-size:13px;line-height:1.6;color:{SLATE};padding-top:9px">
                  <a href="mailto:{e(email)}" style="color:{SLATE};text-decoration:none">{e(email)}</a><br />
                  <a href="{BASE}" style="color:{SEA};text-decoration:none">{e(site)}</a>
                </div>
              </td>
              <td valign="middle" style="padding-left:22px">
                <a href="{BASE}" style="text-decoration:none">
                  <img src="{src('logo.png')}" width="54" height="68" alt="The Tide"
                       style="display:block;width:54px;height:68px;border:0" />
                </a>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
"""


def main() -> None:
    for out, src, note in (
        (
            HERE / 'signature-email.html',
            hosted,
            'This one loads its images from the deployed site, so it shows\n'
            '         broken images until public/signature/ is live.',
        ),
        (
            HERE / 'signature-email-inline.html',
            inline,
            'This one carries its images inside it, so it works before the\n'
            '         site is deployed — but Outlook on Windows will not show them.',
        ),
    ):
        out.write_text(build(src, note))
        print('wrote', out, f'({out.stat().st_size // 1024}KB)')


if __name__ == '__main__':
    main()
