"""Generate `signature-email.html`, the version you paste into a mail client.

The copy lives in `signature.html` and nowhere else: this reads the name, role,
email address and site out of that page's EDIT ME block and writes the table
markup around them. Edit `signature.html`, run `render.sh`, and the PNG and the
pasteable signature stay in step.

Why the markup looks the way it does — mail clients are not browsers:

  * Tables, not flexbox or grid. Outlook on Windows renders through Word, which
    has no flex layout at all.
  * Inline styles only. Gmail strips <style> blocks out of a pasted signature.
  * The photo and the name are images. The photo is round because the PNG is
    round (Outlook drops border-radius on images), and the name is an image
    because Baloo 2 is a web font, which no mail client will download.
  * Every image is an absolute https:// URL on the site, so it still loads for
    a reader who has nothing but the email. That means the signature only works
    once the site carrying `public/signature/` has been deployed.
"""

import html
import re
from pathlib import Path

from PIL import Image

HERE = Path(__file__).parent
SOURCE = HERE / 'signature.html'
OUT = HERE / 'signature-email.html'

BASE = 'https://thetide.co.nz'

INK = '#23313c'
SEA = '#45758c'
SKY = '#a2c5d3'
SLATE = '#5a6672'
SAND = '#f0e7d6'
SAND_LIGHT = '#faf5ea'

FONT = "'Helvetica Neue', Helvetica, Arial, sans-serif"


def grab(pattern: str) -> str:
    m = re.search(pattern, SOURCE.read_text(), re.S)
    if not m:
        raise SystemExit(f'could not find {pattern!r} in signature.html')
    return re.sub(r'\s+', ' ', m.group(1)).strip()


def main() -> None:
    name = grab(r'<p class="name">(.*?)</p>')
    role = grab(r'<p class="role">(.*?)<span>')
    outlet = grab(r'<em>(.*?)</em>')
    email = grab(r'</svg>\s*(\S+@\S+?)\s*</div>')
    site = grab(r'</svg>\s*((?:www\.)?[\w.-]+\.\w{2,}(?:\.\w{2})?)\s*</div>\s*</div>')

    # name.png is rendered at 2x and placed at half its pixel size, so it
    # stays sharp on a retina screen.
    name_png = HERE.parent.parent / 'public' / 'signature' / 'name.png'
    name_w, name_h = (d // 2 for d in Image.open(name_png).size)

    e = html.escape
    doc = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>The Tide — email signature (paste this)</title>
  </head>
  <body style="margin:0;padding:24px;background:#ffffff">
    <!-- GENERATED by build-email.py from signature.html — edit that page, then
         run render.sh. Changes made here are overwritten on the next render.

         To install: open this file in a browser, select the signature, copy,
         and paste it into your mail client's signature box. -->
    <table cellpadding="0" cellspacing="0" border="0" role="presentation"
           style="border-collapse:separate;border-spacing:0;background:{SAND_LIGHT};border:2px solid rgba(69,117,140,0.3);border-radius:14px;font-family:{FONT}">
      <tr>
        <td style="padding:18px 22px 18px 20px" valign="middle">
          <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="border-collapse:collapse">
            <tr>
              <td valign="middle" style="padding-right:20px">
                <img src="{BASE}/signature/portrait.png" width="112" height="112" alt="{e(name)}"
                     style="display:block;width:112px;height:112px;border:0" />
              </td>
              <td valign="middle" style="font-family:{FONT}">
                <img src="{BASE}/signature/name.png" width="{name_w}" height="{name_h}" alt="{e(name)}"
                     style="display:block;width:{name_w}px;height:{name_h}px;border:0" />
                <div style="height:2px;margin:9px 0 10px;background:rgba(69,117,140,0.32);border-radius:1px"></div>
                <div style="font-family:{FONT};font-size:12px;font-weight:bold;letter-spacing:1.6px;text-transform:uppercase;color:{INK};line-height:1.2">
                  {e(role)} <span style="color:{SKY};font-weight:normal">&nbsp;|&nbsp;</span> <span style="color:{SEA}">{e(outlet)}</span>
                </div>
                <div style="font-family:{FONT};font-size:13px;line-height:1.6;color:{SLATE};padding-top:9px">
                  <a href="mailto:{e(email)}" style="color:{SLATE};text-decoration:none">{e(email)}</a><br />
                  <a href="{BASE}" style="color:{SEA};text-decoration:none">{e(site)}</a>
                </div>
              </td>
              <td valign="middle" style="padding-left:22px">
                <a href="{BASE}" style="text-decoration:none">
                  <img src="{BASE}/signature/logo.png" width="54" height="68" alt="The Tide"
                       style="display:block;width:54px;height:68px;border:0" />
                </a>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
"""
    OUT.write_text(doc)
    print('wrote', OUT)


if __name__ == '__main__':
    main()
